name: Build LaTeX PDF

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX and latexmk
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: Compile LaTeX document
      run: |
        mkdir -p docs
        latexmk -pdf -output-directory=docs main.tex

    - name: Commit and push compiled PDF
