name: Build LaTeX PDF

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # update to latest

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Compile main.tex
      run: |
        mkdir -p docs
        pdflatex -output-directory=docs main.tex
        pdflatex -output-directory=docs main.tex  # run twice for references

    - name: Commit and push compiled PDF
      env:
        TOKEN: ${{ secrets.GH_PAT }}  # your personal access token
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add docs/main.pdf
        git commit -m "Auto-compile and update PDF" || echo "No changes to commit"
        git push
